# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FFXIV Pocket Guide
email: imjoshdrink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of mobile friendly guides to help players navigate group content in Final Fantasy XIV. Guide content has been compiled from video guides produced by MTQCapture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ffxiv.joshdrink.com" # the base hostname & protocol for your site, e.g. http://example.com

repository: joshdrink/joshdrink.github.io

twitter_username: ff14pocketguide
github_username:  joshdrink

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - assets/node_modules
  - assets/bower_components
  - assets_old/node_modules
  - assets_old/bower_components
  - _ffxiv_guides/in_progress
  - _ffxiv_guides/templates
  - temp_guides
collections:
    ffxiv_guides:
        output: true
        permalink: /:title
